//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pregunta9.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersonas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AgregarPersona(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AgregarPersonaAsync(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificarPersona(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModificarPersonaAsync(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarPersona(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EliminarPersonaAsync(int ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Pregunta9.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Pregunta9.ServiceReference1.WebService1Soap>, Pregunta9.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerPersonas() {
            return base.Channel.ObtenerPersonas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerPersonasAsync() {
            return base.Channel.ObtenerPersonasAsync();
        }
        
        public string AgregarPersona(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id) {
            return base.Channel.AgregarPersona(ci, nombre, apellido, edad, direccion, psw, rol_id);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPersonaAsync(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id) {
            return base.Channel.AgregarPersonaAsync(ci, nombre, apellido, edad, direccion, psw, rol_id);
        }
        
        public string ModificarPersona(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id) {
            return base.Channel.ModificarPersona(ci, nombre, apellido, edad, direccion, psw, rol_id);
        }
        
        public System.Threading.Tasks.Task<string> ModificarPersonaAsync(int ci, string nombre, string apellido, int edad, string direccion, string psw, int rol_id) {
            return base.Channel.ModificarPersonaAsync(ci, nombre, apellido, edad, direccion, psw, rol_id);
        }
        
        public string EliminarPersona(int ci) {
            return base.Channel.EliminarPersona(ci);
        }
        
        public System.Threading.Tasks.Task<string> EliminarPersonaAsync(int ci) {
            return base.Channel.EliminarPersonaAsync(ci);
        }
    }
}
